dist: bionic
compiler: clang
language: ruby
matrix:
  include:
    - rvm: 2.6.5
      os: linux
      arch: ppc64le
      env:
        - VPYTHON_BYPASS="manually managed python not supported by chrome operations"
addons:
  apt:
    packages:
      - clang
      - pkg-config
      - python3
      - python2.7
      - ninja-build
      - patch
bundler_args: --jobs=4 --retry=3
before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then gem update bundler; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then gem update --system; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" -a "$TRAVIS_RUBY_VERSION" == "system" ]; then sudo gem install bundler; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" -a "$TRAVIS_RUBY_VERSION" != "system" ]; then gem update --system; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" -a "$TRAVIS_RUBY_VERSION" != "system" ]; then gem update bundler; fi
script:
  - git submodule update --init
  - bundle exec rake spec binary --trace
cache:
  bundler: true
